### ISSUE TITLE
Can Record MP4?

### ISSUE THREAD

**Issue by zulitejay** [PittYao/Rtsp2WebRTCForLinux#1]

**Comment by PittYao** [comment]
> _No description provided._

This is playing the rtsp stream on the web. Record mp4 with ffmpeg

**Comment by zulitejay** [comment]
Thanks!
How do I use ffmpeg to record mp4 in this project

**Comment by PittYao** [comment]
> Thanks!
> How do I use ffmpeg to record mp4 in this project
This project does not support，Play it, not record it 。Search ffmpeg to record MP4

**Comment by PittYao** [comment]
> Thanks!
> How do I use ffmpeg to record mp4 in this project

This project does not support recording.Playing rtsp is not recording rtsp .Search ffmpeg to record MP4
